name: avanti
description: "Avanti — self-guided audio tours (Flutter + Supabase)"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # --- Core / backend ---
  supabase_flutter: ^2.9.1
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.7

  # --- UI / Utils ---
  cached_network_image: ^3.3.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

  # --- Mapa / GPS ---
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^12.0.0

  # --- Descargas / Almacenamiento local ---
  dio: ^5.7.0
  crypto: ^3.0.6
  path_provider: ^2.1.5
  isar: ^3.1.0+1
  just_audio: ^0.10.4
  path: ^1.9.1
  audio_session: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/images/
